/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AgencyOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationEventWorkRequest;
import Business.WorkQueue.EducationEventWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author reddy
 */
public class CreateDonationRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateDonationRequestJPanel
     */
    JPanel container;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem ecosystem;
    public CreateDonationRequestJPanel(JPanel container, UserAccount account, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container = container;
        this.account = account;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contactPersonTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contactEmailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        elevatorPitchTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(20, 30, 120, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact Email:");
        add(jLabel7);
        jLabel7.setBounds(260, 460, 180, 29);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Elevator Pitch:");
        add(jLabel8);
        jLabel8.setBounds(260, 500, 180, 29);
        add(titleTextField);
        titleTextField.setBounds(460, 252, 258, 30);
        add(amountTextField);
        amountTextField.setBounds(460, 332, 258, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Donation Request");
        add(jLabel1);
        jLabel1.setBounds(250, 130, 500, 70);
        add(descriptionTextField);
        descriptionTextField.setBounds(460, 372, 258, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Title:");
        add(jLabel2);
        jLabel2.setBounds(260, 260, 100, 29);
        add(contactPersonTextField);
        contactPersonTextField.setBounds(460, 412, 258, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Category:");
        add(jLabel3);
        jLabel3.setBounds(260, 300, 140, 29);
        add(contactEmailTextField);
        contactEmailTextField.setBounds(460, 452, 258, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount:");
        add(jLabel4);
        jLabel4.setBounds(260, 340, 130, 29);
        add(categoryTextField);
        categoryTextField.setBounds(460, 292, 258, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact Person:");
        add(jLabel5);
        jLabel5.setBounds(260, 420, 190, 29);

        createButton.setBackground(new java.awt.Color(0, 0, 0));
        createButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create Event");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton);
        createButton.setBounds(390, 620, 170, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description:");
        add(jLabel6);
        jLabel6.setBounds(260, 380, 160, 29);

        elevatorPitchTextArea.setColumns(20);
        elevatorPitchTextArea.setRows(5);
        jScrollPane2.setViewportView(elevatorPitchTextArea);

        add(jScrollPane2);
        jScrollPane2.setBounds(460, 500, 258, 80);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/international-childrens-day_136441_1280x553 - Copy.jpg"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, 0, 1920, 829);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        Component[] comps = container.getComponents();
        for(Component c: comps) {
            if(c instanceof ManageDonationJPanel) {
                ManageDonationJPanel panel = (ManageDonationJPanel) c;
                panel.populateTable();
            }
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(titleTextField.getText().equals("") || categoryTextField.getText().equals("") || amountTextField.getText().equals("") || descriptionTextField.getText().equals("") || contactPersonTextField.getText().equals("")|| contactEmailTextField.getText().equals("") || elevatorPitchTextArea.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"One or more fields are empty");
            return;
        }
        if (!titleTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid title!!!");
            return;
        }
        
        if (!categoryTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Category!!!");
            return;
        }
        
        if (!amountTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Amount!!!");
            return;
        }
        
        if (!descriptionTextField.getText().matches("[A-Za-z0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Description!!!");
            return;
        }
        
        if (!contactPersonTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Name for contact person!!!");
            return;
        }
        
        if (!contactEmailTextField.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Email ID!!!");
            return;
        }

        
        try{
            DonationEventWorkRequest request = new DonationEventWorkRequest();
            request.setEventName(titleTextField.getText());
            request.setCategory(categoryTextField.getText());
            request.setFundingAmount(amountTextField.getText());
            request.setDescription(descriptionTextField.getText());
            request.setContactPerson(contactPersonTextField.getText());
            request.setContactEmail(contactEmailTextField.getText());
            request.setElevatorPitch(elevatorPitchTextArea.getText());
            request.setSender(account);
            request.setStatus("Sent to Agencies");
            request.setNgoName(enterprise.getName());

            Organization org = null;
            for(Network network : ecosystem.getNetworkList()){
                for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                    for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof AgencyOrganization){
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(request);
                account.getQueue().getWorkRequestList().add(request);
            }
            JOptionPane.showMessageDialog(null, "Grant Request Created Successfully. Agencies notified!");
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Enter valid data!");
        }

        titleTextField.setText("");
        amountTextField.setText("");
        contactPersonTextField.setText("");
        elevatorPitchTextArea.setText("");
        contactEmailTextField.setText("");
        categoryTextField.setText("");
        descriptionTextField.setText("");
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField contactEmailTextField;
    private javax.swing.JTextField contactPersonTextField;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextArea elevatorPitchTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
