/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author reddy
 */
public class CreateEducationalWorkshopJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEducationalWorkshopJPanel
     */
    JPanel container;
    UserAccount account;
    Enterprise enterprise;
    EcoSystem ecosystem;
    public CreateEducationalWorkshopJPanel(JPanel container, UserAccount account, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container = container;
        this.account = account;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eventNameTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        eventDurationTextField = new javax.swing.JTextField();
        topicsTextField = new javax.swing.JTextField();
        instructorCountTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        eventDateTextField = new com.github.lgooddatepicker.components.DatePicker();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Educational Workshop");
        add(jLabel1);
        jLabel1.setBounds(260, 140, 610, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Name:");
        add(jLabel2);
        jLabel2.setBounds(300, 310, 180, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No of Instructors");
        add(jLabel3);
        jLabel3.setBounds(300, 360, 210, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Event Date:");
        add(jLabel4);
        jLabel4.setBounds(300, 410, 170, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Event Duration: (Hrs):");
        add(jLabel5);
        jLabel5.setBounds(300, 510, 250, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Location:");
        add(jLabel6);
        jLabel6.setBounds(300, 460, 150, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Topics:");
        add(jLabel7);
        jLabel7.setBounds(300, 560, 130, 30);
        add(eventNameTextField);
        eventNameTextField.setBounds(560, 310, 258, 30);
        add(locationTextField);
        locationTextField.setBounds(560, 460, 258, 30);
        add(eventDurationTextField);
        eventDurationTextField.setBounds(560, 510, 258, 30);
        add(topicsTextField);
        topicsTextField.setBounds(560, 560, 258, 30);
        add(instructorCountTextField);
        instructorCountTextField.setBounds(560, 360, 258, 30);

        createButton.setBackground(new java.awt.Color(0, 0, 0));
        createButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create Event");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton);
        createButton.setBounds(500, 640, 170, 40);

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(10, 80, 120, 40);
        add(eventDateTextField);
        eventDateTextField.setBounds(560, 410, 290, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/international-childrens-day_136441_1280x553 - Copy.jpg"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1920, 829);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(eventNameTextField.getText().equals("") || instructorCountTextField.getText().equals("") || eventDateTextField.getText().equals("") || locationTextField.getText().equals("") || eventDurationTextField.getText().equals("")|| topicsTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"One or more fields are empty");
                return;
        }
        
        if (!eventNameTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Event Name!!!");
            return;
        }
        
        if (!instructorCountTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid number for Instructor count!!!");
            return;
        }

//        if (!eventDateTextField.getText().matches("^[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2}$")) {
//
//            JOptionPane.showMessageDialog(null, "Please enter a valid date (MM/DD/YYYY)!!!");
//            return;
//        }
        /*        
        if (!locationTextField.getText().matches("[a-zA-Z0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Location!!!");
            return;
        }
        */
        if (!eventDurationTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid number of Hours!!!");
            return;
        }
        
        if (!topicsTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Topic!");
            return;
        }

        
        try{
        String instructorCount = instructorCountTextField.getText();
        String eventDate = eventDateTextField.getText();
        String location = locationTextField.getText();
        String eventDuration = eventDurationTextField.getText();
        String eventName = eventNameTextField.getText();
        String topics = topicsTextField.getText();
        
        EducationEventWorkRequest request = new EducationEventWorkRequest();
        request.setPlace(location);
        request.setDate(eventDate);
        request.setInstructorRequired(instructorCount);
        request.setSender(account);
        request.setStatus("Sent to Corporates");
        request.setNgoName(enterprise.getName());
        request.setDuration(eventDuration);
        request.setTopic(topics);
        request.setEventName(eventName);
        
        Organization org = null;
        for(Network network : ecosystem.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof StudentOrganization){
                        org = organization;
                        break;
                    }
                }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Education Workshop Created Successfully. Schools notified!");
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Enter a valid number for Instructor Required!");
        }
        
        eventNameTextField.setText("");
        eventDateTextField.setText("");
        eventDurationTextField.setText("");
        topicsTextField.setText("");
        instructorCountTextField.setText("");
        locationTextField.setText("");
    }//GEN-LAST:event_createButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        Component[] comps = container.getComponents();
        for(Component c: comps) {
            if(c instanceof ManageEducationalWorkshopJPanel) {
                ManageEducationalWorkshopJPanel panel = (ManageEducationalWorkshopJPanel) c;
                panel.populateTable();
            }
        }
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createButton;
    private com.github.lgooddatepicker.components.DatePicker eventDateTextField;
    private javax.swing.JTextField eventDurationTextField;
    private javax.swing.JTextField eventNameTextField;
    private javax.swing.JTextField instructorCountTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextField topicsTextField;
    // End of variables declaration//GEN-END:variables
}
