/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationEventWorkRequest;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author reddy
 */
public class ViewDonationRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonationRequestJPanel
     */
    private JPanel container;
    private DonationEventWorkRequest request;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    public ViewDonationRequestJPanel(JPanel container, DonationEventWorkRequest request, UserAccount account, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container = container;
        this.request = request;
        this.account = account;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        titleTextField.setText(request.getEventName());
        categoryTextField.setText(request.getCategory());
        amountTextField.setText(request.getFundingAmount());
        descriptionTextField.setText(request.getDescription());
        contactPersonTextField.setText(request.getContactPerson());
        contactEmailTextField.setText(request.getContactEmail());
        elevatorPitchTextArea.setText(request.getElevatorPitch());
        confirmButton.setEnabled(false);
        updateButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        contactPersonTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        contactEmailTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        elevatorPitchTextArea = new javax.swing.JTextArea();
        viewInstructorsButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setText("Title:");
        add(jLabel2);
        jLabel2.setBounds(260, 210, 130, 29);

        contactPersonTextField.setEditable(false);
        add(contactPersonTextField);
        contactPersonTextField.setBounds(450, 370, 258, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setText("Category:");
        add(jLabel3);
        jLabel3.setBounds(260, 250, 160, 29);

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(30, 20, 120, 40);

        contactEmailTextField.setEditable(false);
        add(contactEmailTextField);
        contactEmailTextField.setBounds(450, 410, 258, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setText("Contact Email:");
        add(jLabel7);
        jLabel7.setBounds(260, 410, 200, 29);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setText("Amount:");
        add(jLabel4);
        jLabel4.setBounds(260, 290, 150, 29);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setText("Elevator Pitch:");
        add(jLabel8);
        jLabel8.setBounds(260, 460, 200, 29);

        categoryTextField.setEditable(false);
        add(categoryTextField);
        categoryTextField.setBounds(450, 250, 258, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setText("Contact Person:");
        add(jLabel5);
        jLabel5.setBounds(260, 370, 210, 29);

        titleTextField.setEditable(false);
        add(titleTextField);
        titleTextField.setBounds(450, 210, 258, 30);

        amountTextField.setEditable(false);
        add(amountTextField);
        amountTextField.setBounds(450, 290, 258, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setText("Description:");
        add(jLabel6);
        jLabel6.setBounds(260, 330, 180, 29);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setText("View Donation Request");
        add(jLabel1);
        jLabel1.setBounds(260, 100, 470, 60);

        descriptionTextField.setEditable(false);
        add(descriptionTextField);
        descriptionTextField.setBounds(450, 330, 258, 30);

        elevatorPitchTextArea.setEditable(false);
        elevatorPitchTextArea.setColumns(20);
        elevatorPitchTextArea.setRows(5);
        jScrollPane2.setViewportView(elevatorPitchTextArea);

        add(jScrollPane2);
        jScrollPane2.setBounds(450, 460, 258, 80);

        viewInstructorsButton.setBackground(new java.awt.Color(0, 0, 0));
        viewInstructorsButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        viewInstructorsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewInstructorsButton.setText("View Agencies");
        viewInstructorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInstructorsButtonActionPerformed(evt);
            }
        });
        add(viewInstructorsButton);
        viewInstructorsButton.setBounds(390, 570, 180, 40);

        confirmButton.setBackground(new java.awt.Color(0, 0, 0));
        confirmButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton);
        confirmButton.setBounds(500, 630, 180, 40);

        updateButton.setBackground(new java.awt.Color(0, 0, 0));
        updateButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(290, 630, 180, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/donate - Copy.jpg"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, 0, 1912, 1075);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        Component[] comps = container.getComponents();
        for(Component c: comps) {
            if(c instanceof ManageDonationJPanel) {
                ManageDonationJPanel panel = (ManageDonationJPanel) c;
                panel.populateTable();
            }
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewInstructorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInstructorsButtonActionPerformed
        // TODO add your handling code here:
        RegisteredAgenciesJPanel registeredAgenciesJPanel = new RegisteredAgenciesJPanel(container, request, account, enterprise);
        container.add("RegisteredAgenciesJPanel", registeredAgenciesJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_viewInstructorsButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        titleTextField.setEditable(true);
        categoryTextField.setEditable(true);
        amountTextField.setEditable(true);
        descriptionTextField.setEditable(true);
        contactPersonTextField.setEditable(true);
        contactEmailTextField.setEditable(true);
        elevatorPitchTextArea.setEditable(true);
        updateButton.setEnabled(false);
        confirmButton.setEnabled(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(titleTextField.getText().equals("") || categoryTextField.getText().equals("") || amountTextField.getText().equals("") || descriptionTextField.getText().equals("") || contactPersonTextField.getText().equals("")|| contactEmailTextField.getText().equals("") || elevatorPitchTextArea.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"One or more fields are empty");
            return;
        }
        if (!titleTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid title!!!");
            return;
        }
        
        if (!categoryTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Category!!!");
            return;
        }
        
        if (!amountTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Amount!!!");
            return;
        }
        
        if (!descriptionTextField.getText().matches("[a-zA-Z+]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Description!!!");
            return;
        }
        
        if (!contactPersonTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Name for contact person!!!");
            return;
        }
        
        if (!contactEmailTextField.getText().matches("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Email ID!!!");
            return;
        }
        request.setEventName(titleTextField.getText());
        request.setCategory(categoryTextField.getText());
        request.setFundingAmount(amountTextField.getText());
        request.setDescription(descriptionTextField.getText());
        request.setContactPerson(contactPersonTextField.getText());
        request.setContactEmail(contactEmailTextField.getText());
        request.setElevatorPitch(elevatorPitchTextArea.getText());
        JOptionPane.showMessageDialog(null,"Donation Request updated successfully");
        confirmButton.setEnabled(false);
        updateButton.setEnabled(true);
        titleTextField.setEditable(false);
        categoryTextField.setEditable(false);
        amountTextField.setEditable(false);
        descriptionTextField.setEditable(false);
        contactPersonTextField.setEditable(false);
        contactEmailTextField.setEditable(false);
        elevatorPitchTextArea.setEditable(false);
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField contactEmailTextField;
    private javax.swing.JTextField contactPersonTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextArea elevatorPitchTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewInstructorsButton;
    // End of variables declaration//GEN-END:variables
}
