/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGOAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HeadDoctorApprovalWorkRequest;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author reddy
 */
public class ViewHealthCampJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthCampsJPanel
     */
    private JPanel container;
    private HealthEventWorkRequest request;
    private UserAccount account;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    
    public ViewHealthCampJPanel(JPanel container, HealthEventWorkRequest request, UserAccount account, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.container = container;
        this.request = request;
        this.account = account;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        ngoNameTextField.setText(request.getNgoName());
        eventNameTextField.setText(request.getHealthEventName());
        doctorCountTextField.setText(request.getDoctorCount());
        childrenCountTextField.setText(request.getChildrenCount());
        eventDateTextField.setText(request.getDate());
        locationTextField.setText(request.getPlace());
        eventDurationTextField.setText(request.getDuration());
        confirmButton.setEnabled(false);
        updateButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        eventNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        eventDurationTextField = new javax.swing.JTextField();
        childrenCountTextField = new javax.swing.JTextField();
        doctorCountTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ngoNameTextField = new javax.swing.JTextField();
        viewdoctorsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        eventDateTextField = new com.github.lgooddatepicker.components.DatePicker();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Event Date:");
        add(jLabel4);
        jLabel4.setBounds(240, 390, 180, 30);

        eventNameTextField.setEditable(false);
        add(eventNameTextField);
        eventNameTextField.setBounds(490, 310, 258, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Event Duration: (Hrs)");
        add(jLabel5);
        jLabel5.setBounds(240, 470, 260, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Location:");
        add(jLabel6);
        jLabel6.setBounds(240, 430, 160, 30);

        locationTextField.setEditable(false);
        add(locationTextField);
        locationTextField.setBounds(490, 430, 258, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Children:");
        add(jLabel7);
        jLabel7.setBounds(240, 510, 210, 30);

        eventDurationTextField.setEditable(false);
        add(eventDurationTextField);
        eventDurationTextField.setBounds(490, 470, 258, 30);

        childrenCountTextField.setEditable(false);
        add(childrenCountTextField);
        childrenCountTextField.setBounds(490, 510, 258, 30);

        doctorCountTextField.setEditable(false);
        add(doctorCountTextField);
        doctorCountTextField.setBounds(490, 350, 258, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VIEW HEALTH CAMP");
        add(jLabel1);
        jLabel1.setBounds(270, 140, 500, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Name:");
        add(jLabel2);
        jLabel2.setBounds(240, 310, 190, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No of Doctors:");
        add(jLabel3);
        jLabel3.setBounds(240, 350, 200, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NGO Name:");
        add(jLabel8);
        jLabel8.setBounds(240, 270, 180, 30);

        ngoNameTextField.setEditable(false);
        add(ngoNameTextField);
        ngoNameTextField.setBounds(490, 270, 258, 30);

        viewdoctorsButton.setText("View Doctors");
        viewdoctorsButton.setBackground(new java.awt.Color(0, 0, 0));
        viewdoctorsButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        viewdoctorsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewdoctorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdoctorsButtonActionPerformed(evt);
            }
        });
        add(viewdoctorsButton);
        viewdoctorsButton.setBounds(430, 590, 170, 40);

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(40, 30, 100, 40);

        updateButton.setBackground(new java.awt.Color(0, 0, 0));
        updateButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(320, 650, 170, 40);

        confirmButton.setBackground(new java.awt.Color(0, 0, 0));
        confirmButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton);
        confirmButton.setBounds(510, 650, 170, 40);

        eventDateTextField.setEnabled(false);
        add(eventDateTextField);
        eventDateTextField.setBounds(490, 390, 290, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/international-childrens-day_136441_1280x553 - Copy.jpg"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, 0, 1920, 829);
    }// </editor-fold>//GEN-END:initComponents

    private void viewdoctorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdoctorsButtonActionPerformed
        // TODO add your handling code here:
        RegisteredDoctorsJPanel registeredDoctorsJPanel = new RegisteredDoctorsJPanel(container, request, account, enterprise);
        container.add("RegisteredDoctorsJPanel", registeredDoctorsJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_viewdoctorsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        eventNameTextField.setEditable(true);
        doctorCountTextField.setEditable(true);
        eventDateTextField.setEnabled(true);
        locationTextField.setEditable(true);
        eventDurationTextField.setEditable(true);
        childrenCountTextField.setEditable(true);
        updateButton.setEnabled(false);
        confirmButton.setEnabled(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        if(eventNameTextField.getText().equals("") || doctorCountTextField.getText().equals("") || eventDateTextField.getText().equals("") || locationTextField.getText().equals("") || eventDurationTextField.getText().equals("")|| childrenCountTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"One or more fields are empty");
                return;
        }
        
        if (!eventNameTextField.getText().matches("[A-Za-z]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Event Name!!!");
            return;
        }
        
        if (!doctorCountTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid number for Doctor count!!!");
            return;
        }
     /*
        if (!locationTextField.getText().matches("[a-zA-Z0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid Location!!!");
            return;
        }
        */
        if (!eventDurationTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid number of Hours!!!");
            return;
        }
        
        if (!childrenCountTextField.getText().matches("[0-9]+$")) {

            JOptionPane.showMessageDialog(null, "Please enter a valid number for Children count!!!");
            return;
        }
        
        int c = Integer.parseInt(childrenCountTextField.getText()) ;
        int d = Integer.parseInt(doctorCountTextField.getText()) ;
        if (c<d)
        {
             JOptionPane.showMessageDialog(null, "Number of children cannot be less than doctor count!!!");
            return;
        }
        request.setHealthEventName(eventNameTextField.getText());
        request.setDoctorCount(doctorCountTextField.getText());
        request.setDate(eventDateTextField.getText());
        request.setPlace(locationTextField.getText());
        request.setDuration(eventDurationTextField.getText());
        request.setChildrenCount(childrenCountTextField.getText());
        JOptionPane.showMessageDialog(null,"Health camp updated successfully");
        confirmButton.setEnabled(false);
        updateButton.setEnabled(true);
        eventNameTextField.setEditable(false);
        doctorCountTextField.setEditable(false);
        eventDateTextField.setEnabled(false);
        locationTextField.setEditable(false);
        eventDurationTextField.setEditable(false);
        childrenCountTextField.setEditable(false);
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField childrenCountTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField doctorCountTextField;
    private com.github.lgooddatepicker.components.DatePicker eventDateTextField;
    private javax.swing.JTextField eventDurationTextField;
    private javax.swing.JTextField eventNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JTextField ngoNameTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewdoctorsButton;
    // End of variables declaration//GEN-END:variables
}
