/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HeadDoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HeadDoctorApprovalWorkRequest;
import Business.WorkQueue.HealthEventWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adity
 */
public class DocEventRegistrationJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    HealthEventWorkRequest request;
    UserAccount account;
    Organization organization;
    EcoSystem ecosystem;

    /**
     * Creates new form DocEventRegistrationJPanel
     */
    public DocEventRegistrationJPanel(JPanel userProcessContainer, HealthEventWorkRequest request, UserAccount account, Organization organization, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.organization = organization;
        this.ecosystem = ecosystem;
        ngoTextBox.setText(request.getNgoName());
        doctorsRequiredTextField.setText(request.getDoctorCount());
        dateTextField.setText(request.getDate());
        venueTextField.setText(request.getDate());
        eventDurationTextField.setText(request.getDuration());
        eventNameTextField.setText(request.getHealthEventName());
        registerJButton.setEnabled(true);
        registerEnabled();
    }

    public void registerEnabled() {
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(org instanceof HeadDoctorOrganization){
                        for(WorkRequest r : org.getWorkQueue().getWorkRequestList()){
                                HeadDoctorApprovalWorkRequest managerReq = (HeadDoctorApprovalWorkRequest) r;
                                if (request == managerReq.getWorkRequest() && managerReq.getSender() == account && (managerReq.getStatus().equals("Event Cancelled") || managerReq.getStatus().equals("Pending with HoD") || managerReq.getStatus().equals("Registered"))){
                                    registerJButton.setEnabled(false);
                                    break;
                                } 
                                else {
                                    registerJButton.setEnabled(true);
                                }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ngoTextBox = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        venueTextField = new javax.swing.JTextField();
        doctorsRequiredTextField = new javax.swing.JTextField();
        eventNameTextField = new javax.swing.JTextField();
        eventDurationTextField = new javax.swing.JTextField();
        backButtonJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NGO :");
        add(jLabel2);
        jLabel2.setBounds(900, 190, 100, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctors Required :");
        add(jLabel3);
        jLabel3.setBounds(900, 440, 220, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date :");
        add(jLabel4);
        jLabel4.setBounds(900, 240, 100, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Venue:");
        add(jLabel5);
        jLabel5.setBounds(900, 290, 110, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Event duration:");
        add(jLabel7);
        jLabel7.setBounds(900, 340, 190, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Event Name:");
        add(jLabel8);
        jLabel8.setBounds(900, 390, 160, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Health Checkup Camp Details");
        add(jLabel1);
        jLabel1.setBounds(870, 50, 572, 53);

        ngoTextBox.setEditable(false);
        ngoTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngoTextBoxActionPerformed(evt);
            }
        });
        add(ngoTextBox);
        ngoTextBox.setBounds(1110, 190, 211, 30);

        dateTextField.setEditable(false);
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });
        add(dateTextField);
        dateTextField.setBounds(1110, 240, 211, 30);

        venueTextField.setEditable(false);
        venueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venueTextFieldActionPerformed(evt);
            }
        });
        add(venueTextField);
        venueTextField.setBounds(1110, 290, 211, 30);

        doctorsRequiredTextField.setEditable(false);
        doctorsRequiredTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsRequiredTextFieldActionPerformed(evt);
            }
        });
        add(doctorsRequiredTextField);
        doctorsRequiredTextField.setBounds(1110, 440, 211, 30);

        eventNameTextField.setEditable(false);
        eventNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameTextFieldActionPerformed(evt);
            }
        });
        add(eventNameTextField);
        eventNameTextField.setBounds(1110, 390, 211, 30);

        eventDurationTextField.setEditable(false);
        eventDurationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDurationTextFieldActionPerformed(evt);
            }
        });
        add(eventDurationTextField);
        eventDurationTextField.setBounds(1110, 340, 211, 30);

        backButtonJButton.setBackground(new java.awt.Color(0, 0, 0));
        backButtonJButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        backButtonJButton.setForeground(new java.awt.Color(255, 255, 255));
        backButtonJButton.setText("Back");
        backButtonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonJButtonActionPerformed(evt);
            }
        });
        add(backButtonJButton);
        backButtonJButton.setBounds(240, 10, 120, 40);

        registerJButton.setBackground(new java.awt.Color(0, 0, 0));
        registerJButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        registerJButton.setForeground(new java.awt.Color(255, 255, 255));
        registerJButton.setText("Register");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });
        add(registerJButton);
        registerJButton.setBounds(1050, 520, 140, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doc1.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void ngoTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngoTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngoTextBoxActionPerformed

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void venueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venueTextFieldActionPerformed

    private void doctorsRequiredTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsRequiredTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorsRequiredTextFieldActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void eventNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameTextFieldActionPerformed

    private void eventDurationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDurationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventDurationTextFieldActionPerformed

    private void backButtonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        Component[] comps = userProcessContainer.getComponents();
        for (Component c : comps) {
            if (c instanceof DoctorWorkAreaJPanel) {
                DoctorWorkAreaJPanel panel = (DoctorWorkAreaJPanel) c;
                panel.populateEventRequestTable();
                panel.populateRegistrationsTable();
            }
        }
    }//GEN-LAST:event_backButtonJButtonActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
        String date = dateTextField.getText();
        
        Organization org = null;
        HeadDoctorApprovalWorkRequest managerRequest = new HeadDoctorApprovalWorkRequest();
        managerRequest.setDate(date);
        managerRequest.setSender(account);
        managerRequest.setStatus("Pending with HoD");
        managerRequest.setWorkRequest(request);
        for(Network network : ecosystem.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(organization instanceof HeadDoctorOrganization){
                        managerRequest.setReceiver(organization.getUserAccountDirectory().getUserAccount(account.getEmp().getManagerID()));
                        org = organization;
                    }
                }
            }
        }
        if(org!=null){
            org.getWorkQueue().getWorkRequestList().add(managerRequest);
            account.getQueue().getWorkRequestList().add(managerRequest);
        }
        JOptionPane.showMessageDialog(null, "Registration request sent to HoD for Approval");
        registerJButton.setEnabled(false);
        
    }//GEN-LAST:event_registerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonJButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField doctorsRequiredTextField;
    private javax.swing.JTextField eventDurationTextField;
    private javax.swing.JTextField eventNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField ngoTextBox;
    private javax.swing.JButton registerJButton;
    private javax.swing.JTextField venueTextField;
    // End of variables declaration//GEN-END:variables
}
