/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HeadDoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.StudentCommunityOrganization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.HeadDoctorApprovalWorkRequest;
import Business.WorkQueue.StudentApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adity
 */
public class StudentEventRegistrationJPanel extends javax.swing.JPanel {
     
    private JPanel userProcessContainer;
    Organization organization;
    EducationEventWorkRequest request;
    UserAccount account;
    EcoSystem ecosystem;

    /**
     * Creates new form StudentEventRegistrationJPanel
     */
    

    public StudentEventRegistrationJPanel(JPanel userProcessContainer, EducationEventWorkRequest request, UserAccount userAccount, StudentOrganization studentOrganization, EcoSystem ecosystem) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.request = request;
    this.account = userAccount;
    this.organization = (StudentOrganization)studentOrganization;
    this.ecosystem = ecosystem;
    numberOfInstructors.setText(request.getInstructorRequired());
    dateTextField.setText(request.getDate());
    venueTextField.setText(request.getPlace());
    ngonameTextField.setText(request.getNgoName());
    workshopNameTextField.setText(request.getEventName());
    subjectTaughtTextField.setText(request.getTopic());
    eventDurationTextField.setText(request.getDuration());
    //adminNotesTextField.setText(request.getNotes());
    registerEnabled();
    }

    public void registerEnabled() {
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(org instanceof StudentCommunityOrganization){
                        for(WorkRequest r : org.getWorkQueue().getWorkRequestList()){
                                StudentApprovalWorkRequest managerReq = (StudentApprovalWorkRequest) r;
                                if (request == managerReq.getEventRequest() && managerReq.getSender() == account && (managerReq.getStatus().equals("Event Cancelled") || managerReq.getStatus().equals("Pending with Club") || managerReq.getStatus().equals("Registered"))){
                                    registerButton.setEnabled(false);
                                    break;
                                } 
                                else {
                                    registerButton.setEnabled(true);
                                }
                        }
                    }
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ngonameTextField = new javax.swing.JTextField();
        workshopNameTextField = new javax.swing.JTextField();
        numberOfInstructors = new javax.swing.JTextField();
        venueTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        eventDurationTextField = new javax.swing.JTextField();
        subjectTaughtTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NGO Name :");
        add(jLabel2);
        jLabel2.setBounds(500, 210, 180, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Workshop Name :");
        add(jLabel9);
        jLabel9.setBounds(500, 250, 230, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number of Instructors Required :");
        add(jLabel3);
        jLabel3.setBounds(500, 290, 370, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date :");
        add(jLabel4);
        jLabel4.setBounds(500, 340, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Venue:");
        add(jLabel5);
        jLabel5.setBounds(500, 380, 130, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject to be taught:");
        add(jLabel6);
        jLabel6.setBounds(500, 420, 260, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Event duration: (Hrs)");
        add(jLabel7);
        jLabel7.setBounds(500, 460, 240, 30);
        add(ngonameTextField);
        ngonameTextField.setBounds(880, 220, 240, 30);
        add(workshopNameTextField);
        workshopNameTextField.setBounds(880, 260, 240, 30);
        add(numberOfInstructors);
        numberOfInstructors.setBounds(880, 300, 240, 30);
        add(venueTextField);
        venueTextField.setBounds(880, 380, 240, 30);
        add(dateTextField);
        dateTextField.setBounds(880, 340, 240, 30);

        eventDurationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDurationTextFieldActionPerformed(evt);
            }
        });
        add(eventDurationTextField);
        eventDurationTextField.setBounds(880, 460, 240, 30);
        add(subjectTaughtTextField);
        subjectTaughtTextField.setBounds(880, 420, 240, 30);

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(30, 30, 110, 40);

        registerButton.setBackground(new java.awt.Color(0, 0, 0));
        registerButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        add(registerButton);
        registerButton.setBounds(730, 530, 130, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Educational Workshop Details");
        add(jLabel1);
        jLabel1.setBounds(500, 80, 640, 60);
        add(jLabel10);
        jLabel10.setBounds(0, 0, 0, 0);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clg3 - Copy.jpg"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 0, 1918, 1022);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        Component[] comps = userProcessContainer.getComponents();
        for(Component c: comps) {
            if(c instanceof StudentWorkAreaJPanel) {
                StudentWorkAreaJPanel panel = (StudentWorkAreaJPanel) c;
                panel.populateEventRequestTable();
                panel.populateRegistrationsTable();
            }
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void eventDurationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDurationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventDurationTextFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String date = dateTextField.getText();
        StudentApprovalWorkRequest studentRequest = new StudentApprovalWorkRequest() ;
        Organization org = null;
        studentRequest.setDate(date);
        studentRequest.setSender(account);
        studentRequest.setStatus("Pending with Club");
        studentRequest.setEventRequest(request);
        for(Network network : ecosystem.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof StudentCommunityOrganization){
                        studentRequest.setReceiver(o.getUserAccountDirectory().getUserAccount(account.getEmp().getManagerID()));
                        org = o;
                    }
                }
            }
        }        
        if(org!=null){
        org.getWorkQueue().getWorkRequestList().add(studentRequest);
        account.getQueue().getWorkRequestList().add(studentRequest);
        }
        JOptionPane.showMessageDialog(null, "Registration Approval Request Sent!!!");
        registerButton.setEnabled(false);
    }//GEN-LAST:event_registerButtonActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField eventDurationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField ngonameTextField;
    private javax.swing.JTextField numberOfInstructors;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField subjectTaughtTextField;
    private javax.swing.JTextField venueTextField;
    private javax.swing.JTextField workshopNameTextField;
    // End of variables declaration//GEN-END:variables
}
