/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NGOAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.StudentCommunityOrganization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EducationEventWorkRequest;
import Business.WorkQueue.StudentApprovalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.StudentRole.StudentEventRegistrationJPanel;



public class StudentWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    private StudentOrganization studentOrganization;
    private Enterprise studentEnterprise;

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    public StudentWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        this.studentOrganization = (StudentOrganization)organization;
        this.studentEnterprise = enterprise;
        populateEventRequestTable();
        populateRegistrationsTable();
    }
    
    public void populateEventRequestTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestTable.getModel();
        
        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(organization instanceof StudentOrganization){
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                            if(request instanceof EducationEventWorkRequest){
                                EducationEventWorkRequest req = (EducationEventWorkRequest) request;                   
                                Object[] row = new Object[2];
                                row[0] = req;
                                row[1] = req.getNgoName();
                                model.addRow(row);    
                            }
                        }
                    }
                }
            }
        }
    }
     
    public void populateRegistrationsTable(){
        DefaultTableModel model = (DefaultTableModel)registrationStatusJTable.getModel();        
        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(organization instanceof StudentCommunityOrganization){
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                            if(request.getSender() == userAccount){
                                StudentApprovalWorkRequest req = (StudentApprovalWorkRequest) request;
                                Object[] row = new Object[4];
                                row[0] = req;
                                row[1] = req.getEventRequest();
                                row[2] = req.getEventRequest().getNgoName();
                                row[3] = req.getStatus();    
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        registrationStatusJTable = new javax.swing.JTable();
        refreshNgoEventButton = new javax.swing.JButton();
        viewDetailsButton = new javax.swing.JButton();
        refreshEventRegistrationButton = new javax.swing.JButton();
        unregisterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Volunteer Portal");
        add(jLabel1);
        jLabel1.setBounds(540, 70, 480, 53);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NGO Event Table");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel3);
        jLabel3.setBounds(630, 180, 230, 30);

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        workRequestTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Workshop Name", "NGO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(540, 210, 452, 92);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Registrations");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel2);
        jLabel2.setBounds(630, 400, 250, 40);

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        registrationStatusJTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrationStatusJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Workshop Name", "NGO", "Registration Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(registrationStatusJTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(540, 440, 452, 92);

        refreshNgoEventButton.setBackground(new java.awt.Color(0, 0, 0));
        refreshNgoEventButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        refreshNgoEventButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshNgoEventButton.setText("Refresh");
        refreshNgoEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshNgoEventButtonActionPerformed(evt);
            }
        });
        add(refreshNgoEventButton);
        refreshNgoEventButton.setBounds(630, 320, 130, 40);

        viewDetailsButton.setBackground(new java.awt.Color(0, 0, 0));
        viewDetailsButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        viewDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewDetailsButton.setText("View Details");
        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButtonActionPerformed(evt);
            }
        });
        add(viewDetailsButton);
        viewDetailsButton.setBounds(790, 320, 150, 40);

        refreshEventRegistrationButton.setBackground(new java.awt.Color(0, 0, 0));
        refreshEventRegistrationButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        refreshEventRegistrationButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshEventRegistrationButton.setText("Refresh");
        refreshEventRegistrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshEventRegistrationButtonActionPerformed(evt);
            }
        });
        add(refreshEventRegistrationButton);
        refreshEventRegistrationButton.setBounds(630, 560, 130, 40);

        unregisterButton.setBackground(new java.awt.Color(0, 0, 0));
        unregisterButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        unregisterButton.setForeground(new java.awt.Color(255, 255, 255));
        unregisterButton.setText("Unregister");
        unregisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unregisterButtonActionPerformed(evt);
            }
        });
        add(unregisterButton);
        unregisterButton.setBounds(800, 560, 140, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clg3 - Copy.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1918, 1022);
    }// </editor-fold>//GEN-END:initComponents

    private void unregisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unregisterButtonActionPerformed
int selectedRow = registrationStatusJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select row from table!!!");
            return;
        }

        StudentApprovalWorkRequest approvalRequest = (StudentApprovalWorkRequest)registrationStatusJTable.getValueAt(selectedRow, 0);
        EducationEventWorkRequest ngoEvtReq = approvalRequest.getEventRequest();
        
        if(!(approvalRequest.getStatus().equals("Event Cancelled"))){
        ngoEvtReq.getStudentList().remove(userAccount.getEmp());
        if(ngoEvtReq.getStudentWaitList().size() > 0)
        {
            Employee waitlistedEmp = ngoEvtReq.getStudentWaitList().get(0);
            ngoEvtReq.getStudentList().add(waitlistedEmp);
            for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if(organization instanceof StudentOrganization){
                        for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                            if(request.getSender().getEmp() == waitlistedEmp){
                                
                                request.setStatus("Registered");
                                
                                }
                            }
                        }
                    }
                }
            }
        }
        
        approvalRequest.setStatus("Unregistered");
        populateRegistrationsTable();
        JOptionPane.showMessageDialog(null, "Unregistration successful for workshop!");
        }
        else{
            approvalRequest.setStatus("Unregistered");
            JOptionPane.showMessageDialog(null, "Unregistration successful for cancelled event!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_unregisterButtonActionPerformed

    private void refreshNgoEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshNgoEventButtonActionPerformed
    populateEventRequestTable();         // TODO add your handling code here:
    }//GEN-LAST:event_refreshNgoEventButtonActionPerformed

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
        int selectedRow = workRequestTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select row from table!!!");
            return;
        }

        EducationEventWorkRequest request = (EducationEventWorkRequest)workRequestTable.getValueAt(selectedRow, 0);
        StudentEventRegistrationJPanel studentEventRegistrationJPanel = new StudentEventRegistrationJPanel(userProcessContainer, request, userAccount, studentOrganization, ecosystem);
        userProcessContainer.add("StudentEventRegistrationJPanel", studentEventRegistrationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    private void refreshEventRegistrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshEventRegistrationButtonActionPerformed
        // TODO add your handling code here:
        populateRegistrationsTable();
    }//GEN-LAST:event_refreshEventRegistrationButtonActionPerformed

    
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshEventRegistrationButton;
    private javax.swing.JButton refreshNgoEventButton;
    private javax.swing.JTable registrationStatusJTable;
    private javax.swing.JButton unregisterButton;
    private javax.swing.JButton viewDetailsButton;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables

}